### PR TITLE
Aggregate Docker Requests (and styling update)

### PR DESCRIPTION
**Pull request by ngmiller**
### What

Lays the groundwork for performing docker requests against a collection of hosts. Updates UI and adds functionality for https://github.com/lighthouse/lighthouse/pull/60

For sanity, this PR only supports an application create request. Subsequent PRs will support the other endpoints.

### How

The first major unit of work was refactoring the beacon view into an individual component (via angular directives) to support displaying all beacons and instances at once. This greatly simplifies the templating required on the beacon list view and isolates the functionality of a single beacon component.

Created a `deploy-monitor` component and associated model to watch streaming updates as they come in and notify the user which actions have completed and which is currently in progress.

### Testing

I've been using the `busybox:latest` image for testing image pulls. It's small enough to prevent long testing turn-around times. Be sure to remove the container and image created from your docker instance if you want to test the image pull again. Otherwise, the batch processing on Lighthouse will see the image is already present and the stream will go by pretty quick.

screen shot 2015-04-14 at 9 39 56 pm
screen shot 2015-04-14 at 9 39 59 pm
screen shot 2015-04-14 at 9 40 02 pm

### CODE REVIEW

**Comment by ngmiller** [comment]
@lighthouse/owners This is ready for some test action. **Be sure to run bower install to get the styling update** Thanks!

**Comment by cmbrose** [comment]
+1

**Comment by ngmiller** [comment]
@cmbrose This is ready when `application-rollback` is. Feel free to merge at the same time.

**Pull request merged**
